// WIRE CONTRACT ADAPTER. The wire types are generated by tygo from the engine's
// uihub/wsmsg package into ui/src/gen/wsmsg.ts (source of truth; drift-gated by
// `make gen-ts-check` in engine/). This module re-exports them under the names
// the UI imports, adding only the three UI-side conventions the generator does
// not emit: TopicName (alias of the generated `Topic`), VenueID, and
// ScannerSession.
//
// md.indicator keying: single-series indicators (VWAP/EMA/SMA)
// stream under the bare instanceId as the message `key`; MACD streams each slot
// under `${instanceId}#${slot}` (macd/signal/hist). See render/chart/
// indicatorSeries.ts's describeIndicator for slot names.
export * from "../gen/wsmsg";
import type { Topic } from "../gen/wsmsg";

// The UI has always called the topic union `TopicName`; keep that name.
export type TopicName = Topic;

// A venue id is a free-form config slug; the generated types use bare `string`
// for `venue`, but the UI names the concept for readability.
export type VenueID = string;

// Scanner session travels on the message `key` ("premarket" | "rth" |
// "afterhours" | "overnight"). A UI-side convention, not a generated wire type.
export type ScannerSession = "premarket" | "rth" | "afterhours" | "overnight";
